name: Build CLI executables

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r cli/requirements.txt
        pip install pyinstaller

    - name: Build CLI executables
      run: |
        cd cli
        pyinstaller --onefile --name cli cli.py
        
    - name: Upload executables as release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cli/dist/cli.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
